import { ArrayMinSize, IsArray, IsEmpty, IsNotEmpty, IsUUID } from "class-validator";
import { ApiHideProperty, ApiProperty } from "@nestjs/swagger";
import { ProductEntity } from "../products/product.entity";

export class CreateOrderDto {

    @ApiProperty({
        description: 'Unique user identifier generated by the database (UUID v4)',
        example: '123e4567-e89b-12d3-a456-426614174000'
    })
    @IsNotEmpty()
    @IsUUID()
    userId: string;

    @ApiProperty({
        description: 'List of products to include in the order',
        example: [{ "id": "uuid"},{"id": "uuid"}]
    })
    @IsArray()
    @ArrayMinSize(1)
    products: Partial<ProductEntity>[];

    @ApiHideProperty()
    @IsEmpty()
    stripeSessionId: string;

    @ApiHideProperty()
    @IsEmpty()
    status: string;
}